steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/sample-firebase-ai-app-9cee4/cloud-run-source-deploy/cookflow', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/sample-firebase-ai-app-9cee4/cloud-run-source-deploy/cookflow']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cookflow'
      - '--image'
      - 'us-west1-docker.pkg.dev/sample-firebase-ai-app-9cee4/cloud-run-source-deploy/cookflow'
      - '--region'
      - 'us-west1'
      - '--project'
      - 'sample-firebase-ai-app-9cee4'

options:
  logging: CLOUD_LOGGING_ONLY
